/* This file is automatically generated by the DailyBuild script. */
#if 0
// just a dummy section to make the file more like the generated one from the build maching
// note:  if the format of this file changes dramatically, you will have to change 
// CSharpVersionWriter in BuildTools, as we use it to generate src\include\dotNet\AssemblyVersion.cs
// for C# projects
#else // MAX
  #define VERSION_STRING  "Tekken with PDBs T420_RL_x64 02-28-2013 07:59 187215"
  #define VERSION_INT   420
#endif

